name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build Tailwind assets
        run: npm run build
      - name: PHP lint
        run: |
          find wp-content -name "*.php" -print0 | xargs -0 -n1 php -l
